### PR TITLE
Fixes for empty input cases

### LINKED ISSUE #11: Host Cannot Call Plugin
I have five methods defined in the `.proto` file, and only one of them works when calling them in the host. I tried to find out what happened, but it seems like after calling from the host, the default result struct is returned without value.

here are the proto files and generated codes: https://github.com/wshops/wshop-plugin-common

host code
```go
func TestPluginFunction(t *testing.T) {
	ctx := context.Background()
	p, err := pcaptcha.NewCaptchaPlugin(ctx, pcaptcha.CaptchaPluginOption{
		Stdout: os.Stdout,
		Stderr: os.Stderr,
	})
	if err != nil {
		t.Error(err)
	}

	pluginInstance, err := p.Load(ctx, "./plugins/captcha/hcaptcha.wasm")
	if err != nil {
		t.Error(err)
	}

	pi, err := pluginInstance.GetPluginInfo(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("plugin version: ", pi.GetVersion())

	res, err := pluginInstance.VerifyCaptcha(ctx, pcaptcha.VerifyCaptchaRequest{Captcha: "123"})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("verify result: ", res.GetIsValid())

	htmlInput, err := pluginInstance.GetCustomHtmlInputField(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("input html: ", htmlInput.GetHtml())

	htmlHead, err := pluginInstance.GetCustomHtmlHead(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("head html: ", htmlHead.GetHtml())

	htmlBody, err := pluginInstance.GetCustomHtmlBodyEnd(ctx, emptypb.Empty{})
	if err != nil {
		t.Error(err)
	}
	fmt.Println("body html: ", htmlBody.GetHtml())

	t.Cleanup(func() {
		p.Close(ctx)
	})
}
```
---

result:
```
=== RUN   TestPluginFunction
plugin version:  
validating captcha...
verify result:  true
input html:  
head html:  
body html:  
```

---
version
go: `go1.19.2`
go-plugin: `v0.3.0`
sys: `MacOS 13.0.1`
chip: `Apple M1 Max`

### PR DESCRIPTION
**Pull request by mathetake**
This fixes a bug that makes it impossible to call empty-input plugins. It was introduced in #9 

fixes #11 

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

File: gen/host.go [hunk 1]
```diff
@@ -303,23 +303,23 @@ func genPluginMethod(g *protogen.GeneratedFile, f *fileInfo, method *protogen.Me
 	g.P("data, err := request.MarshalVT()")
 	g.P(errorHandling)
 	g.P("dataSize := uint64(len(data))")
-	g.P(`if dataSize == 0 {
```
Comment (mathetake) [inline gen/host.go:306]: before we return early without making requests to the plugin if dataSize==0... that's mistake

**Review by codefromthecrypt — APPROVED** [review]
thanks for the help @mathetake
