### PR TITLE
Fixes for TinyGo 0.26.0

### LINKED ISSUE #7: wasm error running example
Running the host-functions example I get the following error:

```
2022/11/12 14:42:05 Sending a HTTP request...
2022/11/12 14:42:05 wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanic(i32,i32)
	.runtime.lookupPanic()
	.malloc(i32) i32 (recovered by wazero)
wasm stack trace:
	env.log(i32,i32) i64
	.greeter_greet(i32,i32) i64
```

* go version go1.18.7 darwin/arm64
* macOS 12.6.1 
* Chip M1 Max

### PR DESCRIPTION
**Pull request by mathetake**
Fixes #7 #8 

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

### CODE REVIEW

File: gen/host.go [hunk 1]
```diff
@@ -289,7 +289,9 @@ func genPluginMethod(g *protogen.GeneratedFile, f *fileInfo, method *protogen.Me
 	g.P("data, err := request.MarshalVT()")
 	g.P(errorHandling)
 	g.P("dataSize := uint64(len(data))")
-
+	g.P(`if dataSize == 0 {
```
Comment (mathetake) [inline gen/host.go:292]: this is the fix!

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Great! Thanks!

**Comment by codefromthecrypt** [comment]
sorry I had noticed the tinygo problem earlier, but should have escalated it.
